import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
  Row,
  Column,
} from "@react-email/components";

interface KeyMetric {
  label: string;
  value: string;
}

export interface ReportReadyEmailProps {
  userName: string;
  reportName: string;
  generatedAt: string;
  downloadUrl: string;
  keyMetrics: KeyMetric[];
  dashboardUrl: string;
  showBranding?: boolean;
}

export function ReportReadyEmail({
  userName = "there",
  reportName = "Monthly Sales Report",
  generatedAt = "February 27, 2026",
  downloadUrl = "https://example.com/download",
  keyMetrics = [],
  dashboardUrl = "https://example.com/dashboard",
  showBranding = true,
}: ReportReadyEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>Your report &ldquo;{reportName}&rdquo; is ready to download</Preview>
      <Body style={main}>
        <Container style={container}>
          {showBranding && (
            <Text style={logo}>ReportForge</Text>
          )}

          <Heading style={heading}>Your Report is Ready</Heading>

          <Text style={paragraph}>Hi {userName},</Text>

          <Text style={paragraph}>
            Your report <strong>&ldquo;{reportName}&rdquo;</strong> has been
            generated and is ready for download.
          </Text>

          <Section style={infoBox}>
            <Row>
              <Column>
                <Text style={infoLabel}>Report</Text>
                <Text style={infoValue}>{reportName}</Text>
              </Column>
            </Row>
            <Row>
              <Column>
                <Text style={infoLabel}>Generated</Text>
                <Text style={infoValue}>{generatedAt}</Text>
              </Column>
            </Row>
          </Section>

          {keyMetrics.length > 0 && (
            <Section style={metricsSection}>
              <Text style={metricsHeading}>Key Metrics</Text>
              <Section style={metricsTable}>
                {keyMetrics.slice(0, 5).map((metric) => (
                  <Row key={metric.label} style={metricRow}>
                    <Column style={metricLabelCol}>
                      <Text style={metricLabel}>{metric.label}</Text>
                    </Column>
                    <Column style={metricValueCol}>
                      <Text style={metricValue}>{metric.value}</Text>
                    </Column>
                  </Row>
                ))}
              </Section>
            </Section>
          )}

          <Section style={buttonSection}>
            <Button style={button} href={downloadUrl}>
              Download Report
            </Button>
          </Section>

          <Text style={secondaryText}>
            This download link expires in 7 days. You can also access your
            report from your{" "}
            <Link href={dashboardUrl} style={link}>
              dashboard
            </Link>
            .
          </Text>

          <Hr style={hr} />

          {showBranding && (
            <Text style={footer}>
              Generated by ReportForge
            </Text>
          )}
        </Container>
      </Body>
    </Html>
  );
}

export default ReportReadyEmail;

const main = {
  backgroundColor: "#f8fafc",
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif',
};

const container = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  padding: "32px 24px",
  maxWidth: "600px",
  borderRadius: "12px",
};

const logo = {
  fontSize: "20px",
  fontWeight: "700" as const,
  color: "#1e3a5f",
  textAlign: "center" as const,
  margin: "0 0 24px",
};

const heading = {
  fontSize: "24px",
  fontWeight: "700" as const,
  color: "#1e293b",
  textAlign: "center" as const,
  margin: "0 0 24px",
};

const paragraph = {
  fontSize: "15px",
  lineHeight: "1.6",
  color: "#475569",
  margin: "0 0 16px",
};

const infoBox = {
  backgroundColor: "#f8fafc",
  borderRadius: "8px",
  padding: "16px",
  margin: "0 0 24px",
};

const infoLabel = {
  fontSize: "13px",
  color: "#64748b",
  margin: "0 0 2px",
};

const infoValue = {
  fontSize: "15px",
  fontWeight: "600" as const,
  color: "#1e293b",
  margin: "0 0 12px",
};

const metricsSection = {
  margin: "0 0 24px",
};

const metricsHeading = {
  fontSize: "14px",
  fontWeight: "600" as const,
  color: "#334155",
  margin: "0 0 12px",
  textTransform: "uppercase" as const,
  letterSpacing: "0.05em",
};

const metricsTable = {
  backgroundColor: "#f8fafc",
  borderRadius: "8px",
  padding: "4px 16px",
};

const metricRow = {
  borderBottom: "1px solid #e2e8f0",
};

const metricLabelCol = {
  width: "60%",
};

const metricValueCol = {
  width: "40%",
  textAlign: "right" as const,
};

const metricLabel = {
  fontSize: "14px",
  color: "#475569",
  margin: "10px 0",
};

const metricValue = {
  fontSize: "14px",
  fontWeight: "600" as const,
  color: "#1e293b",
  margin: "10px 0",
  textAlign: "right" as const,
};

const buttonSection = {
  textAlign: "center" as const,
  margin: "0 0 24px",
};

const button = {
  backgroundColor: "#1e3a5f",
  color: "#ffffff",
  fontSize: "16px",
  fontWeight: "600" as const,
  padding: "14px 32px",
  borderRadius: "8px",
  textDecoration: "none",
  display: "inline-block",
};

const secondaryText = {
  fontSize: "13px",
  color: "#94a3b8",
  textAlign: "center" as const,
  margin: "0 0 16px",
};

const link = {
  color: "#1e3a5f",
  textDecoration: "underline",
};

const hr = {
  borderColor: "#e2e8f0",
  margin: "24px 0",
};

const footer = {
  fontSize: "12px",
  color: "#94a3b8",
  textAlign: "center" as const,
  margin: "0",
};
