import { describe, it, expect } from "vitest";
import { render } from "@react-email/components";
import { ReportReadyEmail } from "@/lib/email/templates/report-ready";
import { WeeklyDigestEmail } from "@/lib/email/templates/weekly-digest";
import { PaymentFailedEmail } from "@/lib/email/templates/payment-failed";
import { WelcomeEmail } from "@/lib/email/templates/welcome";
import { SubscriptionConfirmedEmail } from "@/lib/email/templates/subscription-confirmed";

describe("ReportReadyEmail", () => {
  it("renders a valid HTML email with user name and report name", async () => {
    const html = await render(
      ReportReadyEmail({
        userName: "Jane Doe",
        reportName: "Q4 Sales Report",
        generatedAt: "January 15, 2026, 10:30 AM",
        downloadUrl: "https://example.com/download/abc123",
        keyMetrics: [
          { label: "Total Revenue", value: "$142,350" },
          { label: "Growth", value: "+23%" },
        ],
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("Jane Doe");
    expect(html).toContain("Q4 Sales Report");
    expect(html).toContain("Download Report");
    expect(html).toContain("https://example.com/download/abc123");
  });

  it("renders key metrics table", async () => {
    const html = await render(
      ReportReadyEmail({
        userName: "Jane",
        reportName: "Report",
        generatedAt: "Jan 15, 2026",
        downloadUrl: "https://example.com/dl",
        keyMetrics: [
          { label: "Total Revenue", value: "$142,350" },
          { label: "Growth", value: "+23%" },
        ],
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("Total Revenue");
    expect(html).toContain("$142,350");
    expect(html).toContain("+23%");
  });

  it("shows ReportForge branding by default", async () => {
    const html = await render(
      ReportReadyEmail({
        userName: "Jane",
        reportName: "Report",
        generatedAt: "Jan 15, 2026",
        downloadUrl: "https://example.com/dl",
        keyMetrics: [],
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("ReportForge");
  });

  it("hides branding when showBranding is false", async () => {
    const html = await render(
      ReportReadyEmail({
        userName: "Jane",
        reportName: "Report",
        generatedAt: "Jan 15, 2026",
        downloadUrl: "https://example.com/dl",
        keyMetrics: [],
        dashboardUrl: "https://example.com/dashboard",
        showBranding: false,
      })
    );
    expect(html).not.toContain("Generated by ReportForge");
  });
});

describe("WeeklyDigestEmail", () => {
  it("renders with report list and top insight", async () => {
    const html = await render(
      WeeklyDigestEmail({
        userName: "John Smith",
        reports: [
          { name: "Weekly Sales", date: "Feb 12, 10:30 AM", downloadUrl: "https://example.com/1" },
          { name: "Social Media", date: "Feb 14, 2:15 PM", downloadUrl: "https://example.com/2" },
        ],
        totalGenerated: 2,
        topInsight: "Revenue grew 23% compared to last quarter.",
        weekRange: "Feb 10 - Feb 16, 2026",
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("John Smith");
    expect(html).toContain("Weekly Sales");
    expect(html).toContain("Social Media");
    expect(html).toContain("Revenue grew 23%");
    expect(html).toContain("Feb 10 - Feb 16, 2026");
  });

  it("shows correct count", async () => {
    const html = await render(
      WeeklyDigestEmail({
        userName: "Test",
        reports: [{ name: "Report 1", date: "Feb 12", downloadUrl: "https://example.com/1" }],
        totalGenerated: 1,
        topInsight: "",
        weekRange: "Feb 10 - Feb 16, 2026",
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("1");
  });
});

describe("PaymentFailedEmail", () => {
  it("renders with retry date and update link", async () => {
    const html = await render(
      PaymentFailedEmail({
        userName: "Jane",
        nextRetryDate: "March 5, 2026",
        updatePaymentUrl: "https://example.com/settings",
        supportEmail: "support@reportforge.com",
      })
    );
    expect(html).toContain("Payment Failed");
    expect(html).toContain("March 5, 2026");
    expect(html).toContain("Update Payment Method");
    expect(html).toContain("support@reportforge.com");
  });
});

describe("WelcomeEmail", () => {
  it("renders onboarding steps and CTAs", async () => {
    const html = await render(
      WelcomeEmail({
        userName: "Alice",
        uploadUrl: "https://example.com/reports/new",
        templatesUrl: "https://example.com/templates",
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("Welcome to ReportForge");
    expect(html).toContain("Alice");
    expect(html).toContain("Upload Your First Dataset");
    expect(html).toContain("Browse Templates");
  });
});

describe("SubscriptionConfirmedEmail", () => {
  it("renders with plan name and perks", async () => {
    const html = await render(
      SubscriptionConfirmedEmail({
        userName: "Bob",
        planName: "Pro",
        dashboardUrl: "https://example.com/dashboard",
      })
    );
    expect(html).toContain("Subscription Confirmed");
    expect(html).toContain("Pro");
    expect(html).toContain("100 reports per month");
    expect(html).toContain("Go to Dashboard");
  });
});
