export { renderReportHtml } from "./html-renderer";
export type { HtmlRenderInput } from "./html-renderer";

import type { BrandingConfig } from "@/types/settings";

/**
 *server-only -- do not import this function in client components.
 */
export async function renderPdf(
  html: string,
  pageSize: "a4" | "letter" = "a4",
  branding?: BrandingConfig
): Promise<Buffer> {
  const puppeteer = await import("puppeteer");
  const browser = await puppeteer.default.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const showRfBranding = branding?.showReportForgeBranding !== false;
    const footerLeft = showRfBranding
      ? "Generated by ReportForge"
      : branding?.footerText
        ? branding.footerText.replace(/"/g, "&quot;").replace(/</g, "&lt;")
        : "";

    const footerTemplate = `
      <div style="width:100%;font-size:9px;color:#94a3b8;padding:0 48px;display:flex;justify-content:space-between;">
        <span>${footerLeft}</span>
        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
      </div>
    `;

    const pdf = await page.pdf({
      format: pageSize === "a4" ? "A4" : "Letter",
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
      displayHeaderFooter: true,
      headerTemplate: "<span></span>",
      footerTemplate,
    });

    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
